extends Node


class_name Enums


enum weaponTypes {MELEE, RANGED}

enum resourceSpawnType {DASH, DROP}

enum resourceRarity {PRIMARY, COMMON, UNCOMMON, RARE, EPIC, LEGENDARY}

enum curiosityType {DIALOG, MERCHANT}

enum merchantMode {BUY, SELL}

enum dialogResourceType {ADD, REMOVE}

enum resourceType {RESOURCE, MATERIAL, CONSUMABLE, BLUEPRINT, WEAPON, AMMUNITION, EQUIPMENT, NONE, MAP_LOCATION, MAP_PATHWAY, STATUS_EFFECT}

enum weaponAttackType {BASIC_MELEE_SWING_FRONT, BASIC_MELEE_SWING_BACK, BASIC_MELEE_STAB, BASIC_RANGED}

enum enemyStates {IDLE, CHASE, DASH, KEEP_DISTANCE, LAUNCH_PROJECTILE}

enum exitDirection {TOP, RIGHT, DOWN, LEFT}

enum segmentType {ROOM, CORRIDOR, DEAD_END, EXIT, SPECIAL_ROOM_DEAD_END}

enum menuType {INVENTORY, MAP}

enum locationType {MYSTERY, SETTLEMENT, RUINS, RETREAT}

enum locationAttribute {ROCK_SLIDES, DARKNESS, EXPOSURE, INFESTATION}

enum equipmentType {LIGHT, OXYGEN_TANK, HELMET, CHEST, PANTS, BOOTS, ACCESSORY}

enum statusEffectType {BLEED, POISON, BURN, HEAL, STAMINA_COST_REDUCTION, SLOWNESS, AWARENESS}

enum statusEffectReceiver {SELF, TARGET}

enum locations {NONE, A_PAST_FORGOTTEN, THE_SETTLEMENT, CENTRAL_PATHWAY, EASTWARD_QUARRIES}

enum cardType {MELEE_DAMAGE, RANGED_DAMAGE, ATTACK_DELAY, HEALTH, MOVEMENT_SPEED, STAMINA_COST, SIGHT, FORTUNE, EFFECT_STRENGTH, CRITICAL_DAMAGE, DANGER}

enum statType {FEROCITY, PERSEVERANCE, AGILITY, PERCEPTION}

enum chestType {CHEST, BASKET}



