extends Node


class_name Enums


enum weaponTypes {MELEE, RANGED}

enum resourceSpawnType {DASH, DROP}

enum resourceRarity {PRIMARY, COMMON, UNCOMMON, RARE, EPIC, LEGENDARY}

enum curiosityType {DIALOG, MERCHANT}

enum merchantMode {BUY, SELL}

enum dialogResourceType {ADD, REMOVE}

enum resourceType {RESOURCE, MATERIAL, CONSUMABLE, BLUEPRINT, WEAPON, AMMUNITION, EQUIPMENT, NONE, MAP_LOCATION, MAP_PATHWAY, STATUS_EFFECT}

enum weaponAttackType {BASIC_MELEE_SWING_FRONT, BASIC_MELEE_SWING_BACK, BASIC_MELEE_STAB, BASIC_RANGED}

enum enemyStates {IDLE, CHASE, DASH, KEEP_DISTANCE, LAUNCH_PROJECTILE}

enum exitDirection {TOP, RIGHT, DOWN, LEFT}

enum segmentType {ROOM, CORRIDOR, DEAD_END, EXIT, SPECIAL_ROOM_DEAD_END}

enum menuType {INVENTORY, MAP}

enum locationType {NONE, MYSTERY, SETTLEMENT, RUINS, RETREAT}

enum locationAttribute {ROCK_SLIDES, DARKNESS, EXPOSURE, INFESTATION}

enum equipmentType {LIGHT, OXYGEN_TANK, BACKPACK, HELMET, CHEST, PANTS, BOOTS, ACCESSORY}

enum statusEffectType {BLEED, POISON, BURN, ON_HIT, HEAL, STAMINA_COST_REDUCTION, SLOWNESS, AWARENESS, QUICK_FEET, HASTE, \
	MELEE_DAMAGE_INCREASE, RANGED_DAMAGE_INCREASE, DAMAGE_INCREASE, STAMINA_RESTORE, STAT_INCREASE}

enum statusEffectReceiver {SELF, TARGET}

enum locations {NONE, A_PAST_FORGOTTEN, THE_SETTLEMENT, CENTRAL_PATHWAY, EASTWARD_QUARRIES_1, EASTWARD_QUARRIES_2, EASTWARD_QUARRIES_3}

enum cardType {MELEE_DAMAGE, RANGED_DAMAGE, ATTACK_DELAY, HEALTH, MOVEMENT_SPEED, STAMINA_COST, SIGHT, FORTUNE, EFFECT_STRENGTH, CRITICAL_DAMAGE, DANGER, \
	MELEE_RANGED, THIRD_ATTACK, KNOCKBACK, PROJECTILE_SPREAD_SPEED, KILL_ATTACK_DELAY_SPEED, KILL_STAMINA, EXHAUSTING_ATTACK, SIGHT_RADIUS_ENTRY, CONSUME_AMMO, \
	DAMAGE_RANGE, EFFECT_DURATION, EFFECT_TAKEN_DURATION, CRIT_CHANCE, CRIT_STAT_INCREASE, CRIT_HEAL, DASHING_DAMAGE}

enum statType {FEROCITY, PERSEVERANCE, AGILITY, PERCEPTION}

enum chestType {CHEST, BASKET}

enum meleeWeaponType {LANCE, SWORD, DAGGER}

enum effectApplyType {APPLY, TICK, HIT}

enum locationRingLevel {NONE, OUTER, INNER, VISITED, CURRENT}

enum equipmentModifierType {FEROCITY, PERSEVERANCE, AGILITY, PERCEPTION, OXYGEN_CAPACITY, LIGHT_RADIUS, MAX_HEALTH, DAMAGE, WEIGHT_CAPACITY}

enum inventoryType {REGULAR, CRAFTING_PLAYER, CRAFTING_STATION, STORAGE_PLAYER, STORAGE_BOX}




